export const TEST_ACTION = "TEST_ACTION";
export const CHANGE_BAUD_RATE = "CHANGE_BAUD_RATE"
export const CHANGE_DATA_BITS = "CHANGE_DATA_BITS"
export const CHANGE_STOP_BITS = "CHANGE_STOP_BITS"
export const CHANGE_PARITY_BITS = "CHANGE_PARITY_BITS" 
export const CHANGE_FLOW_CONTROL = "CHANGE_FLOW_CONTROL" 

export const CHANGE_UART_TX_MESSAGE = "CHANGE_UART_TX_MESSAGE" 
export const APPEND_CMD_TERMINAL = "APPEND_CMD_TERMINAL" 
export const CHANGE_UART_CONNECTION_STATUS = "CHANGE_UART_CONNECTION_STATUS"
export const CHANGE_SAVE_SETTINGS = "CHANGE_SAVE_SETTINGS"

export const LOAD_SAVE_SETTINGS = "LOAD_SAVE_SETTINGS"